# Generated by Django 3.0.8 on 2020-09-27 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_email', models.EmailField(max_length=254)),
                ('mentor', models.CharField(blank=True, max_length=255)),
                ('mentor_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CLAIMED', 'Claimed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=9)),
                ('title', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('claimed_datetime', models.DateTimeField(editable=False, null=True)),
                ('closed_datetime', models.DateTimeField(editable=False, null=True)),
                ('owner', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mentorq_api.Ticket')),
                ('rating', models.SmallIntegerField(choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')])),
                ('comments', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
