# Generated by Django 3.0.8 on 2020-08-09 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorq_api', '0003_auto_20200802_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='id',
            new_name='ticket',
        ),
    ]
