# Generated by Django 3.0.8 on 2020-08-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorq_api', '0003_auto_20200802_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
