# Generated by Django 3.0.8 on 2020-10-03 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorq_api', '0004_auto_20200826_1057'),
        ('mentorq_api', '0004_auto_20200809_2205'),
    ]

    operations = [
    ]
