# Generated by Django 3.0.8 on 2020-09-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorq_api', '0005_auto_20200912_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
