# Generated by Django 3.0.8 on 2020-09-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorq_api', '0004_auto_20200809_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
