# Generated by Django 3.0.14 on 2022-07-31 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorq_api', '0007_ticket_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorFeedback',
            fields=[
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mentorq_api.Ticket')),
                ('mentor_rating', models.SmallIntegerField(choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')])),
                ('mentor_comments', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Mentor Feedback',
                'verbose_name_plural': 'Mentor Feedback',
            },
        ),
    ]
