# Generated by Django 3.0.8 on 2020-09-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorq_api', '0007_auto_20200914_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='name',
            new_name='owner',
        ),
    ]
